-- One-time Snowflake setup for the staff pipeline.
-- Run as a role that can create DB/schema/objects (adjust names to match .env / dbt).

CREATE DATABASE IF NOT EXISTS EMPLOYEES_ETL;
USE DATABASE EMPLOYEES_ETL;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS MART;

USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT EMPLOYEES_CSV
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
  EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE EMPLOYEES_STAGE
  FILE_FORMAT = EMPLOYEES_CSV;

CREATE OR REPLACE TABLE EMPLOYEES_RAW (
  NAME    VARCHAR,
  TITLE   VARCHAR,
  OFFICE  VARCHAR,
  ADDRESS VARCHAR,
  PHONE   VARCHAR
);

-- Optional: narrow grants for the Airflow/dbt service user.
-- GRANT USAGE ON DATABASE EMPLOYEES_ETL TO ROLE YOUR_ROLE;
-- GRANT USAGE ON ALL SCHEMAS IN DATABASE EMPLOYEES_ETL TO ROLE YOUR_ROLE;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA EMPLOYEES_ETL.RAW TO ROLE YOUR_ROLE;
-- GRANT CREATE TABLE ON SCHEMA EMPLOYEES_ETL.STAGING TO ROLE YOUR_ROLE;
-- GRANT CREATE TABLE ON SCHEMA EMPLOYEES_ETL.MART TO ROLE YOUR_ROLE;
